//! Merged per-query GPU verification (#13): ONE GPU run per query asserts BOTH
//! (a) per-node exact rows + rows/schema-derived cost vs the `.cpu.txt` golden
//! AND (b) the final RESULT. Helpers + the `gpu_test!` macro live in common/mod.rs.
//!
//! `gpu_test!(dataset, sf, query, device, mode)` — the result mode is EXPLICIT per
//! call site so golden-vs-live-oracle is visible at a glance:
//!   golden_exact  = static result golden, exact compare (fail-closed: missing panics);
//!   golden_approx = static result golden, 1e-12 float-tolerant (q14/q39);
//!   oracle        = live CPU-oracle compare, NO golden — for results too large to
//!                   commit as text (>= 256KB; e.g. anti-join ~240MB/1.2M rows);
//!   skip          = per-node only (non-deterministic LIMIT).
//! per-node cost is ALWAYS asserted (read-only) regardless of mode.
#![cfg(not(feature = "rust-only"))]
// Device label 'tp1_standard' and the derived fn names follow the suite convention.
#![allow(non_snake_case)]
#[macro_use]
mod common;

// ── TPC-H (the GPU-supported set) ───────────────────────────────────────────
gpu_test!(tpch, 1, scan_limit, tp1_standard, golden_exact);
gpu_test!(tpch, 1, filter_project, tp1_standard, oracle);    // >256KB result
gpu_test!(tpch, 1, aggregate_groupby, tp1_standard, golden_exact);
gpu_test!(tpch, 1, semi_join, tp1_standard, oracle);        // >256KB result
gpu_test!(tpch, 1, anti_join, tp1_standard, oracle);        // >256KB result
gpu_test!(tpch, 1, nested_loop_join, tp1_standard, golden_exact);
gpu_test!(tpch, 1, cross_join, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q1, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q2, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q3, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q4, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q5, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q6, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q7, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q8, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q9, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q10, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q11, tp1_standard, oracle);              // >256KB result
gpu_test!(tpch, 1, q12, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q13, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q14, tp1_standard, golden_approx);
gpu_test!(tpch, 1, q15, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q16, tp1_standard, oracle);              // >256KB result
gpu_test!(tpch, 1, q17, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q18, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q19, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q20, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q21, tp1_standard, golden_exact);
gpu_test!(tpch, 1, q22, tp1_standard, golden_exact);

gpu_test!(tpch, 1, shuffle_additive, tp1_standard, golden_exact);
gpu_test!(tpch, 1, shuffle_additive_avg, tp1_standard, golden_exact);
// STDDEV/VAR at tp1 (single-partition make_std/make_variance). golden_approx_std
// (1e-11): cuDF's variance algo diverges from DataFusion's Welford by ~2e-12 —
// more than the 1e-12 sum/avg convention. See GpuResultMode doc.
gpu_test!(tpch, 1, shuffle_stddev, tp1_standard, golden_approx_std);

// ── H200/tp8: real 8-way partitioning ───────────────────────────────────────
// One GPU run asserts per-node Σ-over-8 rows+cost vs the tp8-standard .cpu.txt
// (generated by the #13 CpuNodeExecutor) AND the final result (decimal SUM → exact).
// q6 = no shuffle; shuffle_additive = Hash-repartition via Spark-murmur3.
gpu_test!(tpch, 1, q6, tp8_standard, golden_exact);
gpu_test!(tpch, 1, shuffle_additive, tp8_standard, golden_exact);
// AVG at real 8-way: state = (sum,count), merged Σsum/Σcount per hash bucket.
gpu_test!(tpch, 1, shuffle_additive_avg, tp8_standard, golden_exact);
// q1: canonical AVG carrier (3 avgs + 4 sums + count, GROUP BY rf,ls) — real 8-way
// #13 at tp8-standard. Exercises the running column-offset (avgs before count).
gpu_test!(tpch, 1, q1, tp8_standard, golden_exact);
// STDDEV/VAR at real 8-way: Welford [count,mean,m2] state merged via cuDF MERGE_M2
// per hash bucket (stddev_samp/pop + var_samp/pop, all 4 finalize branches).
//
// QUARANTINED as flaky — ticket #103 (llm-wiki/tickets.md). Intermittently SIGSEGVs
// (exit 139) in the GpuAggregate final merge on the shad-gpu H200 (the same host CI's
// gpu-tests job uses), or fails as a contained `vector::reserve` Err — two failure
// signatures from identical inputs, i.e. nondeterministic, not broken. Suspected
// origin: the N-way Welford merge; tp1 (no merge) never crashes. Not caused by the
// executors refactor (reproduces at both old and new memory tiers, upstream of every
// golden comparison).
// IF YOU SEE THIS FAIL LOCALLY, check #103 before assuming your change caused it — it
// has already cost one wrongly-diagnosed "regression" and an unnecessary rollback.
// Cost of disabling: this is the ONLY coverage of the 8-way Welford M2 merge path.
// The tp8 goldens are deliberately LEFT IN PLACE. Re-enable when #103 is fixed.
// gpu_test!(tpch, 1, shuffle_stddev, tp8_standard, golden_approx_std);

// ── TPC-DS (GPU-operational set) ────────────────────────────────────────────
gpu_test!(tpcds, 1, q1, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q3, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q4, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q5, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q6, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q7, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q8, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q10, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q11, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q12, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q13, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q14, tp1_standard, golden_approx);
gpu_test!(tpcds, 1, q15, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q16, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q17, tp1_standard, golden_exact);
// (#96) Real-8-way per-partition JOINs. The CPU-#13 oracle runs
// PartitionMode::Partitioned joins per-partition (child0[p] ⋈ child1[p]), matching
// vanilla DataFusion (all q17 joins are Partitioned 8→8) and the GPU C++ MAP arm.
// q17: mixed count/avg/stddev over 7 real-8-way joins (golden_approx_std for the
// GPU-cuDF-M2 stddev). join_int: minimal 1-key fact-dim join (oracle mode).
gpu_test!(tpcds, 1, q17, tp8_standard, golden_approx_std);
gpu_test!(tpch, 1, join_int, tp8_standard, oracle);
// (#97-a) Real-8-way per-partition NON-inner Partitioned joins (semi=RightSemi,
// anti=RightAnti, left=Left, each 8→8). oracle mode (>256KB results): the GPU output
// is checked against a LIVE CPU-oracle run, so anti's NOT-IN null handling is gated
// at both levels.
gpu_test!(tpch, 1, semi_join, tp8_standard, oracle);
gpu_test!(tpch, 1, anti_join, tp8_standard, oracle);
gpu_test!(tpch, 1, left_join, tp8_standard, oracle);
// TPC-H join queries at real 8-way (Partitioned Inner, int keys, mergeable sum
// aggs); small results → golden_exact (consumes the cpu_node13-owned .result.txt).
// Multi-func aggs (q8, q12: 2 sums) verify on CI only — the local flatc
// aggr_funcs-vector bug truncates multi-func aggs; single-agg queries verify locally
// too. q3 (#99 SPM/TopK fix): ORDER BY revenue LIMIT 10, SPM k-way-merges + fetches.
gpu_test!(tpch, 1, q3, tp8_standard, golden_exact);
gpu_test!(tpch, 1, q5, tp8_standard, golden_exact);
gpu_test!(tpch, 1, q7, tp8_standard, golden_exact);
gpu_test!(tpch, 1, q8, tp8_standard, golden_exact);
gpu_test!(tpch, 1, q9, tp8_standard, golden_exact);
gpu_test!(tpch, 1, q12, tp8_standard, golden_exact);
gpu_test!(tpch, 1, q19, tp8_standard, golden_exact);
// q13: grouped count over a Partitioned LEFT-outer (nested group-bys, single-count
// each level → local-reliable). golden_exact (small custdist result).
gpu_test!(tpch, 1, q13, tp8_standard, golden_exact);
gpu_test!(tpcds, 1, q18, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q19, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q20, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q21, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q22, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q23, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q24, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q25, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q26, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q29, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q30, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q31, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q32, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q33, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q34, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q35, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q37, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q40, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q41, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q42, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q43, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q45, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q46, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q48, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q50, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q51, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q52, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q53, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q54, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q55, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q56, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q58, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q59, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q60, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q62, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q63, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q64, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q65, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q68, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q69, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q71, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q73, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q74, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q75, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q79, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q80, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q81, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q82, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q83, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q84, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q85, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q88, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q89, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q90, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q91, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q92, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q93, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q94, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q95, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q96, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q97, tp1_standard, golden_exact);
gpu_test!(tpcds, 1, q98, tp1_standard, oracle);             // >256KB result
gpu_test!(tpcds, 1, q99, tp1_standard, golden_exact);

// ── registry verification ───────────────────────────────────────────────────
/// Owns `full_table_gpu` + `partitioned_gpu`, and enforces the cross-mode golden
/// invariant (an enabled GPU mode needs its same-device `.cpu.txt`). Both are
/// cfg'd off under rust-only, where gpu_test! emits neither test nor registration —
/// an uncfg'd reverse check would then see an empty inventory and fail spuriously.
#[cfg(not(feature = "rust-only"))]
#[test]
fn registry_matches_csv_gpu_columns() {
    common::registry::assert_registry_matches_csv(&["full_table_gpu", "partitioned_gpu"], &[]);
}

// NOTE: the cross-mode golden invariant deliberately does NOT live here. It reads
// only the CSV and the goldens on disk — no GPU, no inventory — so gating it behind
// this binary's `not(rust-only)` build would mean it could only ever fail on a host
// that has a GPU toolchain. That is the same "guard that cannot go red where it
// matters" hole test_ci_coverage exists to close. It runs in the CPU tier instead,
// in test_query_plan.rs.
