//! Merged per-query GPU verification, real 8-way partitioned execution.
//!
//! ONE GPU run per query asserts BOTH (a) per-node exact rows + rows/schema-derived
//! cost vs the `partitioned-tp8-standard.cpu.txt` golden (generated by the
//! partitioned CPU executor) AND (b) the final RESULT. Helpers + the
//! `gpu_partitioned_test!` macro live in common/mod.rs; the single-partition half of
//! the suite is test_gpu_full_table.rs.
//!
//! `gpu_partitioned_test!(dataset, sf, query, label, mode)` — the device argument is
//! the combined golden label (`partitioned_tp8_standard`), so the golden filename is
//! reconstructible from the call site with no lookup, and a label whose mode prefix
//! disagrees with the macro cannot pass silently. The result mode is EXPLICIT per
//! call site so golden-vs-live-oracle is visible at a glance:
//!   golden_exact      = static result golden, exact compare (fail-closed: missing panics);
//!   golden_approx_std = static result golden, 1e-11 float-tolerant (cuDF M2 stddev);
//!   oracle            = live CPU-oracle compare, NO golden — for results too large to
//!                       commit as text (>= 256KB);
//!   skip              = per-node only.
//! per-node cost is ALWAYS asserted (read-only) regardless of mode.
#![cfg(not(feature = "rust-only"))]
#[macro_use]
mod common;

/// This target's reading of a case-list entry: the full correctness check at real 8-way.
///
/// Two arms, one per golden label. The label is matched as a LITERAL token, so a row
/// carrying neither known label fails to compile rather than expanding to nothing —
/// see the header of `common/gpu_cases.inc`.
macro_rules! gpu_case {
    ($dataset:ident, $sf:literal, $query:ident, partitioned_tp8_standard, $mode:ident) => {
        gpu_partitioned_test!($dataset, $sf, $query, partitioned_tp8_standard, $mode);
    };
    // The tp1 rows belong to test_gpu_full_table; drop them here.
    ($dataset:ident, $sf:literal, $query:ident, full_table_tp1_standard, $mode:ident) => {};
}

include!("common/gpu_cases.inc");


// ── registry verification ───────────────────────────────────────────────────
/// Owns `partitioned_gpu`. Cfg'd off under rust-only, where gpu_partitioned_test!
/// emits neither test nor registration — an uncfg'd reverse check would then see an
/// empty inventory and fail spuriously.
#[cfg(not(feature = "rust-only"))]
#[test]
fn registry_matches_csv_partitioned_gpu_column() {
    common::registry::assert_registry_matches_csv(&["partitioned_gpu"], &[]);
}
