//! Merged per-query GPU verification, real 8-way partitioned execution.
//!
//! ONE GPU run per query asserts BOTH (a) per-node exact rows + rows/schema-derived
//! cost vs the `partitioned-tp8-standard.cpu.txt` golden (generated by the
//! partitioned CPU executor) AND (b) the final RESULT. Helpers + the
//! `gpu_partitioned_test!` macro live in common/mod.rs; the single-partition half of
//! the suite is test_gpu_full_table.rs.
//!
//! `gpu_partitioned_test!(dataset, sf, query, label, mode)` — the device argument is
//! the combined golden label (`partitioned_tp8_standard`), so the golden filename is
//! reconstructible from the call site with no lookup, and a label whose mode prefix
//! disagrees with the macro cannot pass silently. The result mode is EXPLICIT per
//! call site so golden-vs-live-oracle is visible at a glance:
//!   golden_exact      = static result golden, exact compare (fail-closed: missing panics);
//!   golden_approx_std = static result golden, 1e-11 float-tolerant (cuDF M2 stddev);
//!   oracle            = live CPU-oracle compare, NO golden — for results too large to
//!                       commit as text (>= 256KB);
//!   skip              = per-node only.
//! per-node cost is ALWAYS asserted (read-only) regardless of mode.
#![cfg(not(feature = "rust-only"))]
#[macro_use]
mod common;

// ── TPC-H ───────────────────────────────────────────────────────────────────
// One GPU run asserts per-node Σ-over-8 rows+cost vs the partitioned-tp8-standard
// .cpu.txt (generated by the partitioned CPU executor) AND the final result
// (decimal SUM → exact). q6 = no shuffle; shuffle_additive = Hash-repartition via
// Spark-murmur3.
gpu_partitioned_test!(tpch, 1, q6, partitioned_tp8_standard, golden_exact);
gpu_partitioned_test!(tpch, 1, shuffle_additive, partitioned_tp8_standard, golden_exact);
// AVG at real 8-way: state = (sum,count), merged Σsum/Σcount per hash bucket.
gpu_partitioned_test!(tpch, 1, shuffle_additive_avg, partitioned_tp8_standard, golden_exact);
// q1: canonical AVG carrier (3 avgs + 4 sums + count, GROUP BY rf,ls) — real 8-way
// at tp8-standard. Exercises the running column-offset (avgs before count).
gpu_partitioned_test!(tpch, 1, q1, partitioned_tp8_standard, golden_exact);
// STDDEV/VAR at real 8-way: Welford [count,mean,m2] state merged via cuDF MERGE_M2
// per hash bucket (stddev_samp/pop + var_samp/pop, all 4 finalize branches).
//
// QUARANTINED as flaky — ticket #103 (llm-wiki/tickets.md). Intermittently SIGSEGVs
// (exit 139) in the GpuAggregate final merge on the shad-gpu H200 (the same host CI's
// gpu-tests job uses), or fails as a contained `vector::reserve` Err — two failure
// signatures from identical inputs, i.e. nondeterministic, not broken. Suspected
// origin: the N-way Welford merge; the full-table tier (no merge) never crashes. Not
// caused by the executors refactor (reproduces at both old and new memory tiers,
// upstream of every golden comparison).
// IF YOU SEE THIS FAIL LOCALLY, check #103 before assuming your change caused it — it
// has already cost one wrongly-diagnosed "regression" and an unnecessary rollback.
// Cost of disabling: this is the ONLY coverage of the 8-way Welford M2 merge path.
// The tp8 goldens are deliberately LEFT IN PLACE. Re-enable when #103 is fixed.
// gpu_partitioned_test!(tpch, 1, shuffle_stddev, partitioned_tp8_standard, golden_approx_std);

// (#96) Real-8-way per-partition JOINs. The partitioned CPU oracle runs
// PartitionMode::Partitioned joins per-partition (child0[p] ⋈ child1[p]), matching
// vanilla DataFusion (all q17 joins are Partitioned 8→8) and the GPU C++ MAP arm.
// q17: mixed count/avg/stddev over 7 real-8-way joins (golden_approx_std for the
// GPU-cuDF-M2 stddev). join_int: minimal 1-key fact-dim join (oracle mode).
gpu_partitioned_test!(tpcds, 1, q17, partitioned_tp8_standard, golden_approx_std);
gpu_partitioned_test!(tpch, 1, join_int, partitioned_tp8_standard, oracle);
// (#97-a) Real-8-way per-partition NON-inner Partitioned joins (semi=RightSemi,
// anti=RightAnti, left=Left, each 8→8). oracle mode (>256KB results): the GPU output
// is checked against a LIVE CPU-oracle run, so anti's NOT-IN null handling is gated
// at both levels.
gpu_partitioned_test!(tpch, 1, semi_join, partitioned_tp8_standard, oracle);
gpu_partitioned_test!(tpch, 1, anti_join, partitioned_tp8_standard, oracle);
gpu_partitioned_test!(tpch, 1, left_join, partitioned_tp8_standard, oracle);
// TPC-H join queries at real 8-way (Partitioned Inner, int keys, mergeable sum
// aggs); small results → golden_exact (consumes the cpu_partitioned-owned
// .result.txt). Multi-func aggs (q8, q12: 2 sums) verify on CI only — the local flatc
// aggr_funcs-vector bug truncates multi-func aggs; single-agg queries verify locally
// too. q3 (#99 SPM/TopK fix): ORDER BY revenue LIMIT 10, SPM k-way-merges + fetches.
gpu_partitioned_test!(tpch, 1, q3, partitioned_tp8_standard, golden_exact);
gpu_partitioned_test!(tpch, 1, q5, partitioned_tp8_standard, golden_exact);
gpu_partitioned_test!(tpch, 1, q7, partitioned_tp8_standard, golden_exact);
gpu_partitioned_test!(tpch, 1, q8, partitioned_tp8_standard, golden_exact);
gpu_partitioned_test!(tpch, 1, q9, partitioned_tp8_standard, golden_exact);
gpu_partitioned_test!(tpch, 1, q12, partitioned_tp8_standard, golden_exact);
gpu_partitioned_test!(tpch, 1, q19, partitioned_tp8_standard, golden_exact);
// q13: grouped count over a Partitioned LEFT-outer (nested group-bys, single-count
// each level → local-reliable). golden_exact (small custdist result).
gpu_partitioned_test!(tpch, 1, q13, partitioned_tp8_standard, golden_exact);

// ── registry verification ───────────────────────────────────────────────────
/// Owns `partitioned_gpu`. Cfg'd off under rust-only, where gpu_partitioned_test!
/// emits neither test nor registration — an uncfg'd reverse check would then see an
/// empty inventory and fail spuriously.
#[cfg(not(feature = "rust-only"))]
#[test]
fn registry_matches_csv_partitioned_gpu_column() {
    common::registry::assert_registry_matches_csv(&["partitioned_gpu"], &[]);
}
