#!/usr/bin/env bash
# gen_duckdb_goldens.sh — regenerate the TPC-H and TPC-H+V query RESULT goldens that the
# bare-cudf GPU tests (cpp/tests/gpu/test_tpch.cpp, cpp/tests/gpu/test_tpchv.cpp) assert
# against.
#
# The goldens are DuckDB's answers to the same queries over the SAME parquet files the
# GPU test reads, so a mismatch means the hand-written cudf operator chain is wrong —
# not that the two sides read different data. They are committed (a few rows each) even
# though the sf40 DATA is gitignored, so CI can compare without regenerating 40GB.
#
# COMMITTED, NOT FOLKLORE: if a golden ever has to change, it is regenerated by this
# script and the diff is reviewable — never hand-edited.
#
# THE SQL LIVES IN testdata/tpch_query_sql.sh, not here. benchmarks/duckdb_minimal.sh
# times DuckDB on these same queries; two copies of the text would drift, and a benchmark
# measuring a query the goldens do not describe is a number with no correctness attached.
# This file owns the DATA BINDING (views over parquet) and the golden layout; that file
# owns the query text. Nothing else should be duplicated between them.
#
# Determinism: threads=1 and an explicit ORDER BY in every query with >1 row, so the
# row order is fixed and the file is byte-stable across runs and machines.
#
# Usage:  testdata/gen_duckdb_goldens.sh --sf 40 [--data-dir DIR] [--duckdb PATH]
#                                        [--only TAG[,TAG...]]
#   --data-dir defaults to <repo>/testdata/tpch.sf<SF>; on shad-gpu the datasets live
#   outside the repo, so point it at /home/info/peacock-datasets/testdata/tpch.sf40.
#   --only regenerates a subset (q6,q1,q3,q8,q11v,q12v,q10v,q9v) — the vector goldens over
#   sf40 take minutes each, so a change to one query should not cost a full rerun.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
SF=40
DATA_DIR=""
DUCKDB="${DUCKDB:-duckdb}"
ONLY=""

# shellcheck source=testdata/tpch_query_sql.sh
. "${SCRIPT_DIR}/tpch_query_sql.sh"

while [ $# -gt 0 ]; do
  case "$1" in
    --sf) SF="$2"; shift 2 ;;
    --data-dir) DATA_DIR="$2"; shift 2 ;;
    --duckdb) DUCKDB="$2"; shift 2 ;;
    --only) ONLY=",$2," ; shift 2 ;;
    *) echo "usage: $0 [--sf N] [--data-dir DIR] [--duckdb PATH] [--only TAG,...]" >&2; exit 2 ;;
  esac
done
[ -n "$DATA_DIR" ] || DATA_DIR="${ROOT}/testdata/tpch.sf${SF}"
OUT="${ROOT}/testdata/goldens/tpch.sf${SF}"

command -v "$DUCKDB" >/dev/null 2>&1 || { echo "error: duckdb not found ($DUCKDB)" >&2; exit 1; }
[ -d "$DATA_DIR" ] || { echo "error: data dir not found: $DATA_DIR" >&2; exit 1; }
for t in lineitem orders customer part partsupp supplier nation region; do
  [ -f "${DATA_DIR}/${t}.parquet" ] || { echo "error: missing ${DATA_DIR}/${t}.parquet" >&2; exit 1; }
done
mkdir -p "$OUT"

# --only filter. Default (empty ONLY) runs everything.
want() { [ -z "$ONLY" ] || case "$ONLY" in *",$1,"*) return 0 ;; *) return 1 ;; esac; }

# Every table as a view over its parquet, emitted once. q9v needs partsupp, Q8 needs
# region; rather than track which query needs what, define them all — an unused view costs
# nothing, and a missing one is a failure at the worst possible moment.
views() {
  local t
  for t in lineitem orders customer part partsupp supplier nation region; do
    echo "CREATE VIEW ${t} AS SELECT * FROM read_parquet('${DATA_DIR}/${t}.parquet');"
  done
}

# An erroring DuckDB run writes nothing to stdout, producing a 0-byte golden that is
# INDISTINGUISHABLE from a query that legitimately returned no rows. That ambiguity hid a
# real bug here once (an empty q11v golden that should have had rows). So: run to a temp
# file, check duckdb's exit status explicitly, and only then publish. A genuinely empty
# result is still allowed — it just has to come from a SUCCESSFUL query.
#
# Values are emitted as DuckDB prints them — DECIMAL stays DECIMAL (exact digits, no
# float formatting), which is what lets the GPU side compare exactly rather than within
# a tolerance. -csv -noheader gives just the rows.
duck_to() {
  local out="$1"; shift
  local tmp="${out}.tmp"
  if ! "$DUCKDB" :memory: -csv -noheader -c "PRAGMA threads=1; $(views) $*" \
        > "$tmp" 2>"${tmp}.err"; then
    echo "error: duckdb failed generating $(basename "$out"):" >&2
    sed 's/^/    /' "${tmp}.err" >&2
    rm -f "$tmp" "${tmp}.err"
    exit 1
  fi
  mv "$tmp" "$out"; rm -f "${tmp}.err"
}

run() {
  local name="$1" sql="$2"
  echo "  ${name}"
  duck_to "${OUT}/duckdb_${name}.csv" "$sql"
}

echo "generating goldens from ${DATA_DIR} -> ${OUT}"

want q6 && run q6 "$(sql_q6)"
want q1 && run q1 "$(sql_q1)"
want q3 && run q3 "$(sql_q3)"
want q8 && run q8 "$(sql_q8)"

# ---------------------------------------------------------------------------
# TPC-H+V — the vector queries. Emitted once per selected (q,D) entry from the COMMITTED
# query_params.jsonl, so the golden and the GPU test resolve ${q}/${D} from the same
# source rather than each embedding its own copy of a 96- or 100-float literal.
#
# TWO goldens per entry, on purpose:
#   duckdb_<query>_<id>.csv                 the final query result
#   duckdb_<column>_<id>.count.csv          rows of the BASE table under D, BEFORE any join
#
# The count is named after the EMBEDDING COLUMN, not the query, because that is what it is
# a property of: q12v, q10v and q9v all filter part on p_text_embedding, so a count golden
# per query would be three identical files under three names — the same divergent-copy
# problem this script's SQL split exists to prevent.
# ---------------------------------------------------------------------------

# probe id -> the query it drives. One probe per k tier (10 / 100 / 1000) per embedding
# column, so both the tight and the wide neighbourhood regimes are covered.
#   img_* : ps_image_embedding on partsupp (96 dims)
#   txt_* : p_text_embedding   on part     (100 dims)
# The D of each probe is the k-th nearest distance CALIBRATED AT sf1 over that specific
# column's vectors, which is why an id may not be moved between columns.
gen_vec() {
  local id="$1" D="$2" lit="$3"
  local query col
  case "$id" in
    img_000|img_017|img_034) query=q11v; col=psimage ;;
    txt_000) query=q12v; col=ptext ;;
    txt_017) query=q10v; col=ptext ;;
    txt_034) query=q9v;  col=ptext ;;
    *) echo "error: no query mapped for probe $id" >&2; exit 1 ;;
  esac
  want "$query" || return 0
  echo "  ${query} ${id}"
  duck_to "${OUT}/duckdb_${col}_${id}.count.csv" "$(sql_${col}_count "$D" "$lit")"
  duck_to "${OUT}/duckdb_${query}_${id}.csv" "$(sql_${query} "$D" "$lit")"
}

if [ -f "${ROOT}/testdata/tpch-vec-queries/query_params.jsonl" ]; then
  while IFS=$'\t' read -r vid vD vlit; do
    gen_vec "$vid" "$vD" "$vlit"
  done < <(python3 - "${ROOT}/testdata/tpch-vec-queries/query_params.jsonl" <<'PY'
import json, sys
# one probe per k tier per column; see the gen_vec case statement for the query mapping
WANT = ["img_000", "img_017", "img_034", "txt_000", "txt_017", "txt_034"]
rows = {}
for line in open(sys.argv[1]):
    r = json.loads(line)
    if r["id"] in WANT:
        rows[r["id"]] = (r["D"], "[" + ",".join(repr(float(x)) for x in r["q"]) + "]")
# a probe that silently vanished from the params file would otherwise just produce fewer
# goldens, and the test that needs it would fail much later with a missing-file error
missing = [w for w in WANT if w not in rows]
if missing:
    sys.exit(f"error: query_params.jsonl is missing probes: {missing}")
for w in WANT:
    D, lit = rows[w]
    print(f"{w}\t{D!r}\t{lit}")
PY
)
else
  echo "  vector goldens SKIPPED — query_params.jsonl not found"
fi

echo "done. goldens in ${OUT}:"
ls -la "$OUT"
