#!/usr/bin/env bash
# gen_duckdb_goldens.sh — regenerate the TPC-H query RESULT goldens that the bare-cudf
# GPU test (cpp/tests/gpu/test_tpch.cpp) asserts against.
#
# The goldens are DuckDB's answers to the same queries over the SAME parquet files the
# GPU test reads, so a mismatch means the hand-written cudf operator chain is wrong —
# not that the two sides read different data. They are committed (a few rows each) even
# though the sf40 DATA is gitignored, so CI can compare without regenerating 40GB.
#
# COMMITTED, NOT FOLKLORE: if a golden ever has to change, it is regenerated by this
# script and the diff is reviewable — never hand-edited.
#
# Determinism: threads=1 and an explicit ORDER BY in every query with >1 row, so the
# row order is fixed and the file is byte-stable across runs and machines.
#
# Usage:  testdata/gen_duckdb_goldens.sh --sf 40 [--data-dir DIR] [--duckdb PATH]
#   --data-dir defaults to <repo>/testdata/tpch.sf<SF>; on shad-gpu the datasets live
#   outside the repo, so point it at /home/info/peacock-datasets/testdata/tpch.sf40.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
SF=40
DATA_DIR=""
DUCKDB="${DUCKDB:-duckdb}"

while [ $# -gt 0 ]; do
  case "$1" in
    --sf) SF="$2"; shift 2 ;;
    --data-dir) DATA_DIR="$2"; shift 2 ;;
    --duckdb) DUCKDB="$2"; shift 2 ;;
    *) echo "usage: $0 [--sf N] [--data-dir DIR] [--duckdb PATH]" >&2; exit 2 ;;
  esac
done
[ -n "$DATA_DIR" ] || DATA_DIR="${ROOT}/testdata/tpch.sf${SF}"
OUT="${ROOT}/testdata/goldens/tpch.sf${SF}"

command -v "$DUCKDB" >/dev/null 2>&1 || { echo "error: duckdb not found ($DUCKDB)" >&2; exit 1; }
[ -d "$DATA_DIR" ] || { echo "error: data dir not found: $DATA_DIR" >&2; exit 1; }
for t in lineitem orders customer part supplier nation region; do
  [ -f "${DATA_DIR}/${t}.parquet" ] || { echo "error: missing ${DATA_DIR}/${t}.parquet" >&2; exit 1; }
done
mkdir -p "$OUT"

# Values are emitted as DuckDB prints them — DECIMAL stays DECIMAL (exact digits, no
# float formatting), which is what lets the GPU side compare exactly rather than within
# a tolerance. -csv gives one header line then the rows.
run() {
  local name="$1" sql="$2"
  echo "  ${name}"
  "$DUCKDB" :memory: -csv -noheader -c "
    PRAGMA threads=1;
    CREATE VIEW lineitem AS SELECT * FROM read_parquet('${DATA_DIR}/lineitem.parquet');
    CREATE VIEW orders   AS SELECT * FROM read_parquet('${DATA_DIR}/orders.parquet');
    CREATE VIEW customer AS SELECT * FROM read_parquet('${DATA_DIR}/customer.parquet');
    CREATE VIEW part     AS SELECT * FROM read_parquet('${DATA_DIR}/part.parquet');
    CREATE VIEW supplier AS SELECT * FROM read_parquet('${DATA_DIR}/supplier.parquet');
    CREATE VIEW nation   AS SELECT * FROM read_parquet('${DATA_DIR}/nation.parquet');
    CREATE VIEW region   AS SELECT * FROM read_parquet('${DATA_DIR}/region.parquet');
    ${sql}" > "${OUT}/duckdb_${name}.csv"
}

echo "generating goldens from ${DATA_DIR} -> ${OUT}"

# Q6: sum(l_extendedprice * l_discount) over a date/discount/quantity filter. One row.
# Predicate constants are written as exact decimal literals (0.05 / 0.07) rather than
# TPC-H's '.06 - 0.01' / '.06 + 0.01': identical values, but written so the golden and
# the cudf-side scalars are visibly the same numbers.
run q6 "
  SELECT sum(l_extendedprice * l_discount) AS revenue
  FROM lineitem
  WHERE l_shipdate >= DATE '1994-01-01'
    AND l_shipdate <  DATE '1995-01-01'
    AND l_discount BETWEEN 0.05 AND 0.07
    AND l_quantity < 24;"

# Q1: pricing summary. GROUP BY (l_returnflag, l_linestatus) with 8 aggregates, ordered
# by the group keys. 4 rows.
# ORDER BY is on the two group keys, which are UNIQUE per row here, so the row order is
# total and cannot depend on tie-breaking — the GPU side sorts by the same two keys and
# the rows line up positionally.
# Column types matter for the comparison on the other side, so they are pinned here:
#   sum_qty / sum_base_price / sum_disc_price / sum_charge  DECIMAL (exact)
#   avg_qty / avg_price / avg_disc                          DOUBLE  (DuckDB's AVG over a
#                                                           DECIMAL returns DOUBLE)
#   count_order                                             BIGINT  (exact)
# The AVG columns are the ONLY ones needing a tolerance; see test_tpch.cpp.
run q1 "
  SELECT l_returnflag, l_linestatus,
         sum(l_quantity)                                       AS sum_qty,
         sum(l_extendedprice)                                  AS sum_base_price,
         sum(l_extendedprice * (1 - l_discount))               AS sum_disc_price,
         sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) AS sum_charge,
         avg(l_quantity)                                       AS avg_qty,
         avg(l_extendedprice)                                  AS avg_price,
         avg(l_discount)                                       AS avg_disc,
         count(*)                                              AS count_order
  FROM lineitem
  WHERE l_shipdate <= DATE '1998-09-02'
  GROUP BY l_returnflag, l_linestatus
  ORDER BY l_returnflag, l_linestatus;"

# Q3: shipping priority. customer JOIN orders JOIN lineitem, filters, groupby, sort, top 10.
#
# TIE-BREAK: TPC-H Q3 specifies ORDER BY revenue DESC, o_orderdate — which is NOT a total
# order, so two rows with equal (revenue, o_orderdate) could come back either way round and
# a LIMIT 10 could even include different rows run to run. l_orderkey is appended as a
# final tie-breaker (it is unique per group here) so the ordering is TOTAL and the golden
# is reproducible. The cudf side sorts by the same three keys. Without this the comparison
# would be flaky rather than wrong — the worst kind of test.
run q3 "
  SELECT l_orderkey,
         sum(l_extendedprice * (1 - l_discount)) AS revenue,
         o_orderdate,
         o_shippriority
  FROM customer, orders, lineitem
  WHERE c_mktsegment = 'BUILDING'
    AND c_custkey = o_custkey
    AND l_orderkey = o_orderkey
    AND o_orderdate < DATE '1995-03-15'
    AND l_shipdate  > DATE '1995-03-15'
  GROUP BY l_orderkey, o_orderdate, o_shippriority
  ORDER BY revenue DESC, o_orderdate, l_orderkey
  LIMIT 10;"

# Q8: national market share. SEVEN distinct tables (nation appears twice as n1/n2).
#
# FOUR COLUMNS, NOT THE SPEC'S TWO — deliberate. TPC-H Q8 outputs (o_year, mkt_share), but
# mkt_share is a DIVISION of two sums and DuckDB returns DOUBLE for it (verified:
# typeof(DECIMAL/DECIMAL) = DOUBLE), so it can only be compared within a tolerance. The two
# sums themselves are DECIMAL(38,4) and exact. Emitting them separately lets the test
# compare both EXACTLY and confine the tolerance to the ratio alone; comparing only
# mkt_share would let two compensating errors in the sums cancel inside the division and
# pass unnoticed.
run q8 "
  SELECT o_year,
         sum(CASE WHEN nation = 'BRAZIL' THEN volume ELSE 0 END) AS brazil_volume,
         sum(volume)                                             AS total_volume,
         sum(CASE WHEN nation = 'BRAZIL' THEN volume ELSE 0 END) / sum(volume) AS mkt_share
  FROM (
    SELECT extract(year FROM o_orderdate)        AS o_year,
           l_extendedprice * (1 - l_discount)    AS volume,
           n2.n_name                             AS nation
    FROM part, supplier, lineitem, orders, customer, nation n1, nation n2, region
    WHERE p_partkey = l_partkey
      AND s_suppkey = l_suppkey
      AND l_orderkey = o_orderkey
      AND o_custkey = c_custkey
      AND c_nationkey = n1.n_nationkey
      AND n1.n_regionkey = r_regionkey
      AND r_name = 'AMERICA'
      AND s_nationkey = n2.n_nationkey
      AND o_orderdate BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
      AND p_type = 'ECONOMY ANODIZED STEEL'
  ) AS all_nations
  GROUP BY o_year
  ORDER BY o_year;"

# ---------------------------------------------------------------------------
# TPC-H+V q11 — the vector query. Emitted once per (q,D) entry from the COMMITTED
# query_params.jsonl, so the golden and the GPU test resolve ${q}/${D} from the same
# source rather than each embedding its own copy of a 96-float literal.
#
# array_distance(), not the pgvector <-> operator: DuckDB has no <-> and the committed
# .sql uses it only as notation.
#
# TWO goldens per entry, on purpose:
#   duckdb_q11v_<id>.csv        the final grouped result (ps_partkey, value)
#   duckdb_q11v_<id>.count.csv  the number of partsupp rows under D, BEFORE any join
# The count is the corroboration that matters for a vector query: it pins the row set the
# distance predicate selects, independent of everything the joins and the HAVING do
# afterwards. A final result can coincidentally match while the search returned the wrong
# neighbours; the count cannot.
# An erroring DuckDB run writes nothing to stdout, producing a 0-byte golden that is
# INDISTINGUISHABLE from a query that legitimately returned no rows. That ambiguity hid a
# real bug here once (an empty q11v golden that should have had rows). So: run to a temp
# file, check duckdb's exit status explicitly, and only then publish. A genuinely empty
# result is still allowed — it just has to come from a SUCCESSFUL query.
duck_to() {
  local out="$1"; shift
  local tmp="${out}.tmp"
  if ! "$DUCKDB" :memory: -csv -noheader -c "$*" > "$tmp" 2>"${tmp}.err"; then
    echo "error: duckdb failed generating $(basename "$out"):" >&2
    sed 's/^/    /' "${tmp}.err" >&2
    rm -f "$tmp" "${tmp}.err"
    exit 1
  fi
  mv "$tmp" "$out"; rm -f "${tmp}.err"
}

gen_q11v() {
  local id="$1" D="$2" lit="$3"
  echo "  q11v ${id}"
  duck_to "${OUT}/duckdb_q11v_${id}.count.csv" "
    PRAGMA threads=1;
    CREATE VIEW partsupp AS SELECT * FROM read_parquet('${DATA_DIR}/partsupp.parquet');
    SELECT count(*) FROM partsupp
    WHERE array_distance(ps_image_embedding::FLOAT[96], ${lit}::FLOAT[96]) < ${D};
  "
  duck_to "${OUT}/duckdb_q11v_${id}.csv" "
    PRAGMA threads=1;
    CREATE VIEW partsupp AS SELECT * FROM read_parquet('${DATA_DIR}/partsupp.parquet');
    CREATE VIEW supplier AS SELECT * FROM read_parquet('${DATA_DIR}/supplier.parquet');
    CREATE VIEW nation   AS SELECT * FROM read_parquet('${DATA_DIR}/nation.parquet');
    SELECT ps_partkey, sum(ps_supplycost * ps_availqty) AS value
    FROM partsupp, supplier, nation
    WHERE ps_suppkey = s_suppkey
      AND s_nationkey = n_nationkey
      AND n_name = 'GERMANY'
      AND array_distance(ps_image_embedding::FLOAT[96], ${lit}::FLOAT[96]) < ${D}
    GROUP BY ps_partkey
    HAVING sum(ps_supplycost * ps_availqty) > (
      SELECT sum(ps_supplycost * ps_availqty) * 0.000002
      FROM partsupp, supplier, nation
      WHERE ps_suppkey = s_suppkey AND s_nationkey = n_nationkey AND n_name = 'GERMANY'
    )
    ORDER BY value DESC, ps_partkey;
  "
}

# ORDER BY adds ps_partkey after value: TPC-H q11 orders by value alone, which is not a
# total order once two parts share a value. ps_partkey is unique per group, so appending
# it makes the row order reproducible instead of leaving ties to the engine.
if [ -f "${ROOT}/testdata/tpch-vec-queries/query_params.jsonl" ]; then
  while IFS=$'\t' read -r vid vD vlit; do
    gen_q11v "$vid" "$vD" "$vlit"
  done < <(python3 - "${ROOT}/testdata/tpch-vec-queries/query_params.jsonl" <<'PY'
import json, sys
WANT = {"img_000", "img_017", "img_034"}   # one per k tier (10/100/1000), all image
for line in open(sys.argv[1]):
    r = json.loads(line)
    if r["id"] in WANT:
        lit = "[" + ",".join(repr(float(x)) for x in r["q"]) + "]"
        print(f"{r['id']}\t{r['D']!r}\t{lit}")
PY
)
else
  echo "  q11v SKIPPED — query_params.jsonl not found"
fi

echo "done. goldens in ${OUT}:"
ls -la "$OUT"
